//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEditor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorldDatabase : DbContext
    {
        public WorldDatabase()
            : base("name=WorldDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<creature> creature { get; set; }
        public virtual DbSet<creature_addon> creature_addon { get; set; }
        public virtual DbSet<creature_loot_template> creature_loot_template { get; set; }
        public virtual DbSet<creature_model_info> creature_model_info { get; set; }
        public virtual DbSet<creature_onkill_reputation> creature_onkill_reputation { get; set; }
        public virtual DbSet<creature_template> creature_template { get; set; }
        public virtual DbSet<creature_template_addon> creature_template_addon { get; set; }
        public virtual DbSet<disenchant_loot_template> disenchant_loot_template { get; set; }
        public virtual DbSet<fishing_loot_template> fishing_loot_template { get; set; }
        public virtual DbSet<gameobject> gameobject { get; set; }
        public virtual DbSet<gameobject_loot_template> gameobject_loot_template { get; set; }
        public virtual DbSet<gameobject_template> gameobject_template { get; set; }
        public virtual DbSet<item_loot_template> item_loot_template { get; set; }
        public virtual DbSet<item_template> item_template { get; set; }
        public virtual DbSet<milling_loot_template> milling_loot_template { get; set; }
        public virtual DbSet<pickpocketing_loot_template> pickpocketing_loot_template { get; set; }
        public virtual DbSet<skinning_loot_template> skinning_loot_template { get; set; }
        public virtual DbSet<smart_scripts> smart_scripts { get; set; }
        public virtual DbSet<creature_equip_template> creature_equip_template { get; set; }
        public virtual DbSet<quest_template> quest_template { get; set; }
        public virtual DbSet<creature_questender> creature_questender { get; set; }
        public virtual DbSet<creature_queststarter> creature_queststarter { get; set; }
        public virtual DbSet<gameobject_questender> gameobject_questender { get; set; }
        public virtual DbSet<gameobject_queststarter> gameobject_queststarter { get; set; }
    }
}
