using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DatabaseEditor
{
    public static class DatabaseStructure
    {
        public static Dictionary<string, string> Dictionary;

        public static void InitializeDictionary()
        {
            Dictionary = new Dictionary<string, string>();

            // creature_template
            Dictionary.Add("entry", "Entry");
            Dictionary.Add("difficulty_entry_1", "");
            Dictionary.Add("difficulty_entry_2", "");
            Dictionary.Add("difficulty_entry_3", "");
            Dictionary.Add("KillCredit1", "Kill credit");
            Dictionary.Add("KillCredit2", "Kill credit 2");
            Dictionary.Add("modelid1", "Model A_M");
            Dictionary.Add("modelid2", "Model H_M");
            Dictionary.Add("modelid3", "Model A_F");
            Dictionary.Add("modelid4", "Model H_F");
            Dictionary.Add("name", "Name");
            Dictionary.Add("subname", "Subname");
            Dictionary.Add("IconName", "Icon name");
            Dictionary.Add("gossip_menu_id", "Gossip menu");
            Dictionary.Add("minlevel", "Min level");
            Dictionary.Add("maxlevel", "Max level");
            Dictionary.Add("exp", "Expansion");
            Dictionary.Add("exp_unk", "");
            Dictionary.Add("faction", "Faction");
            Dictionary.Add("npcflag", "NPC flags");
            Dictionary.Add("speed_walk", "Walk");
            Dictionary.Add("speed_run", "Run");
            Dictionary.Add("scale", "Scale");
            Dictionary.Add("rank", "Rank");
            Dictionary.Add("mindmg", "Min dmg");
            Dictionary.Add("maxdmg", "Max dmg");
            Dictionary.Add("dmgschool", "");
            Dictionary.Add("attackpower", "");
            Dictionary.Add("dmg_multiplier", "");
            Dictionary.Add("baseattacktime", "");
            Dictionary.Add("rangeattacktime", "");
            Dictionary.Add("unit_class", "Unit class");
            Dictionary.Add("unit_flags", "Unit flags");
            Dictionary.Add("unit_flags2", "Unit flags 2");
            Dictionary.Add("dynamicflags", "Dynamic flags");
            Dictionary.Add("family", "Family");
            Dictionary.Add("trainer_type", "");
            Dictionary.Add("trainer_spell", "");
            Dictionary.Add("trainer_class", "");
            Dictionary.Add("trainer_race", "");
            Dictionary.Add("minrangedmg", "");
            Dictionary.Add("maxrangedmg", "");
            Dictionary.Add("rangedattackpower", "");
            Dictionary.Add("type", "Type");
            Dictionary.Add("type_flags", "Type flags");
            Dictionary.Add("type_flags2", "Type flags 2");
            Dictionary.Add("lootid", "Loot ID");
            Dictionary.Add("pickpocketloot", "Pick pocket ID");
            Dictionary.Add("skinloot", "Skinning ID");
            Dictionary.Add("resistance1", "");
            Dictionary.Add("resistance2", "");
            Dictionary.Add("resistance3", "");
            Dictionary.Add("resistance4", "");
            Dictionary.Add("resistance5", "");
            Dictionary.Add("resistance6", "");
            Dictionary.Add("spell1", "");
            Dictionary.Add("spell2", "");
            Dictionary.Add("spell3", "");
            Dictionary.Add("spell4", "");
            Dictionary.Add("spell5", "");
            Dictionary.Add("spell6", "");
            Dictionary.Add("spell7", "");
            Dictionary.Add("spell8", "");
            Dictionary.Add("PetSpellDataId", "");
            Dictionary.Add("VehicleId", "");
            Dictionary.Add("mingold", "Min gold");
            Dictionary.Add("maxgold", "Max gold");
            Dictionary.Add("AIName", "");
            Dictionary.Add("MovementType", "Movement type");
            Dictionary.Add("InhabitType", "");
            Dictionary.Add("HoverHeight", "");
            Dictionary.Add("Health_mod", "");
            Dictionary.Add("Mana_mod", "");
            Dictionary.Add("Mana_mod_extra", "");
            Dictionary.Add("Armor_mod", "");
            Dictionary.Add("RacialLeader", "");
            Dictionary.Add("questItem1", "");
            Dictionary.Add("questItem2", "");
            Dictionary.Add("questItem3", "");
            Dictionary.Add("questItem4", "");
            Dictionary.Add("questItem5", "");
            Dictionary.Add("questItem6", "");
            Dictionary.Add("movementId", "");
            Dictionary.Add("RegenHealth", "");
            Dictionary.Add("equipment_id", "Equipment ID");
            Dictionary.Add("mechanic_immune_mask", "");
            Dictionary.Add("flags_extra", "");
            Dictionary.Add("ScriptName", "");
            Dictionary.Add("WDBVerified", "");

            // creature
            Dictionary.Add("guid", "Guid");
            Dictionary.Add("id", "ID");
            Dictionary.Add("map", "Map");
            Dictionary.Add("spawnMask", "Spawn mask");
            Dictionary.Add("phaseMask", "Phase mask");
            Dictionary.Add("modelid", "Model ID");
            //Dictionary.Add("equipment_id", "Equipment ID");
            Dictionary.Add("position_x", "Pos X");
            Dictionary.Add("position_y", "Pos Y");
            Dictionary.Add("position_z", "Pos Z");
            Dictionary.Add("orientation", "Orient.");
            Dictionary.Add("spawntimesecs", "Spawn time");
            Dictionary.Add("spawndist", "Spawn dist.");
            Dictionary.Add("currentwaypoint", "Curr. waypoint");
            Dictionary.Add("curhealth", "Curr. health");
            Dictionary.Add("curmana", "Curr. mana");
            /*Dictionary.Add("MovementType", "Movement type");
            Dictionary.Add("npcflag", "NPC ");
            Dictionary.Add("unit_flags", "");
            Dictionary.Add("dynamicflags", "");*/

            // creature, creature_template addon
            //Dictionary.Add("guid", "");
            Dictionary.Add("path_id", "Path ID");
            Dictionary.Add("mount", "Mount");
            Dictionary.Add("bytes1", "Bytes");
            Dictionary.Add("bytes2", "Bytes 2");
            Dictionary.Add("emote", "Emote");
            Dictionary.Add("auras", "Aura");

            // creature equip template
            //Dictionary.Add("entry", "");
            //Dictionary.Add("id", "");
            Dictionary.Add("itemEntry1", "Item ID");
            Dictionary.Add("itemEntry2", "Item ID 2");
            Dictionary.Add("itemEntry3", "Item ID 3");

            // creature quest starter, ender
            //Dictionary.Add("id", "");
            Dictionary.Add("quest", "Quest");

            // creature model info
            //Dictionary.Add("modelid", "");
            Dictionary.Add("bounding_radius", "Bounding radius");
            Dictionary.Add("combat_reach", "Combat reach");
            Dictionary.Add("gender", "Gender");
            Dictionary.Add("modelid_other_gender", "Other gender");

            // creature on kill reputation
            Dictionary.Add("creature_id", "Creature ID");
            Dictionary.Add("RewOnKillRepFaction1", "Faction");
            Dictionary.Add("RewOnKillRepFaction2", "Faction 2");
            Dictionary.Add("MaxStanding1", "Max standing");
            Dictionary.Add("IsTeamAward1", "Team award");
            Dictionary.Add("RewOnKillRepValue1", "Rep. value");
            Dictionary.Add("MaxStanding2", "Max stading 2");
            Dictionary.Add("IsTeamAward2", "Team award 2");
            Dictionary.Add("RewOnKillRepValue2", "Rep. value 2");
            Dictionary.Add("TeamDependent", "Team dependent");
            Dictionary.Add("CurrencyId1", "Currency ID");
            Dictionary.Add("CurrencyId2", "Currency ID 2");
            Dictionary.Add("CurrencyId3", "Currency ID 3");
            Dictionary.Add("CurrencyCount1", "Currency count");
            Dictionary.Add("CurrencyCount2", "Currency count 2");
            Dictionary.Add("CurrencyCount3", "Currency count 3");

            // creature, skinning, pick pocket loot template
            Dictionary.Add("Entry", "Entry");
            Dictionary.Add("Item", "Item");
            Dictionary.Add("Reference", "Reference");
            Dictionary.Add("Chance", "Chance");
            Dictionary.Add("QuestRequired", "Required quest");
            Dictionary.Add("LootMode", "Loot mode");
            Dictionary.Add("GroupId", "Group ID");
            Dictionary.Add("MinCount", "Min count");
            Dictionary.Add("MaxCount", "Max count");
            Dictionary.Add("Comment", "Comment");

            // quest template
            Dictionary.Add("Id", "ID");
            Dictionary.Add("Method", "");
            Dictionary.Add("Level", "Level");
            Dictionary.Add("MinLevel", "");
            Dictionary.Add("MaxLevel", "");
            Dictionary.Add("ZoneOrSort", "");
            Dictionary.Add("Type", "");
            Dictionary.Add("SuggestedPlayers", "");
            Dictionary.Add("LimitTime", "");
            Dictionary.Add("RequiredClasses", "");
            Dictionary.Add("RequiredRaces", "");
            Dictionary.Add("RequiredSkillId", "");
            Dictionary.Add("RequiredSkill", "");
            Dictionary.Add("RequiredSkillPoints", "");
            Dictionary.Add("RequiredFactionId1", "");
            Dictionary.Add("RequiredFactionId2", "");
            Dictionary.Add("RequiredFactionValue1", "");
            Dictionary.Add("RequiredFactionValue2", "");
            Dictionary.Add("RequiredMinRepFaction", "");
            Dictionary.Add("RequiredMaxRepFaction", "");
            Dictionary.Add("RequiredMinRepValue", "");
            Dictionary.Add("RequiredMaxRepValue", "");
            Dictionary.Add("PrevQuestId", "");
            Dictionary.Add("NextQuestId", "");
            Dictionary.Add("ExclusiveGroup", "");
            Dictionary.Add("NextQuestIdChain", "");
            Dictionary.Add("RewardXPId", "");
            Dictionary.Add("RewardOrRequiredMoney", "Rewards");
            Dictionary.Add("RewardMoneyMaxLevel", "");
            Dictionary.Add("RewardSpell", "");
            Dictionary.Add("RewardSpellCast", "");
            Dictionary.Add("RewardHonor", "");
            Dictionary.Add("RewardHonorMultiplier", "");
            Dictionary.Add("RewardMailTemplateId", "");
            Dictionary.Add("RewardMailDelay", "");
            Dictionary.Add("SourceItemId", "");
            Dictionary.Add("SourceItemCount", "");
            Dictionary.Add("SourceSpellId", "");
            Dictionary.Add("Flags", "Flags");
            Dictionary.Add("SpecialFlags", "");
            Dictionary.Add("MinimapTargetMark", "");
            Dictionary.Add("RewardTitleId", "");
            Dictionary.Add("RequiredPlayerKills", "");
            Dictionary.Add("RewardTalents", "");
            Dictionary.Add("RewardArenaPoints", "");
            Dictionary.Add("RewardSkillId", "");
            Dictionary.Add("RewardSkillPoints", "");
            Dictionary.Add("RewardReputationMask", "");
            Dictionary.Add("QuestGiverPortrait", "");
            Dictionary.Add("QuestTurnInPortrait", "");
            Dictionary.Add("RewardItemId1", "");
            Dictionary.Add("RewardItemId2", "");
            Dictionary.Add("RewardItemId3", "");
            Dictionary.Add("RewardItemId4", "");
            Dictionary.Add("RewardItemCount1", "");
            Dictionary.Add("RewardItemCount2", "");
            Dictionary.Add("RewardItemCount3", "");
            Dictionary.Add("RewardItemCount4", "");
            Dictionary.Add("RewardChoiceItemId1", "");
            Dictionary.Add("RewardChoiceItemId2", "");
            Dictionary.Add("RewardChoiceItemId3", "");
            Dictionary.Add("RewardChoiceItemId4", "");
            Dictionary.Add("RewardChoiceItemId5", "");
            Dictionary.Add("RewardChoiceItemId6", "");
            Dictionary.Add("RewardChoiceItemCount1", "");
            Dictionary.Add("RewardChoiceItemCount2", "");
            Dictionary.Add("RewardChoiceItemCount3", "");
            Dictionary.Add("RewardChoiceItemCount4", "");
            Dictionary.Add("RewardChoiceItemCount5", "");
            Dictionary.Add("RewardChoiceItemCount6", "");
            Dictionary.Add("RewardFactionId1", "");
            Dictionary.Add("RewardFactionId2", "");
            Dictionary.Add("RewardFactionId3", "");
            Dictionary.Add("RewardFactionId4", "");
            Dictionary.Add("RewardFactionId5", "");
            Dictionary.Add("RewardFactionValueId1", "");
            Dictionary.Add("RewardFactionValueId2", "");
            Dictionary.Add("RewardFactionValueId3", "");
            Dictionary.Add("RewardFactionValueId4", "");
            Dictionary.Add("RewardFactionValueId5", "");
            Dictionary.Add("RewardFactionValueIdOverride1", "");
            Dictionary.Add("RewardFactionValueIdOverride2", "");
            Dictionary.Add("RewardFactionValueIdOverride3", "");
            Dictionary.Add("RewardFactionValueIdOverride4", "");
            Dictionary.Add("RewardFactionValueIdOverride5", "");
            Dictionary.Add("PointMapId", "");
            Dictionary.Add("PointX", "");
            Dictionary.Add("PointY", "");
            Dictionary.Add("PointOption", "");
            Dictionary.Add("Title", "Title");
            Dictionary.Add("Objectives", "");
            Dictionary.Add("Details", "");
            Dictionary.Add("EndText", "");
            Dictionary.Add("OfferRewardText", "");
            Dictionary.Add("RequestItemsText", "");
            Dictionary.Add("CompletedText", "");
            Dictionary.Add("RequiredNpcOrGo1", "");
            Dictionary.Add("RequiredNpcOrGo2", "");
            Dictionary.Add("RequiredNpcOrGo3", "");
            Dictionary.Add("RequiredNpcOrGo4", "");
            Dictionary.Add("RequiredNpcOrGoCount1", "");
            Dictionary.Add("RequiredNpcOrGoCount2", "");
            Dictionary.Add("RequiredNpcOrGoCount3", "");
            Dictionary.Add("RequiredNpcOrGoCount4", "");
            Dictionary.Add("RequiredSourceItemId1", "");
            Dictionary.Add("RequiredSourceItemId2", "");
            Dictionary.Add("RequiredSourceItemId3", "");
            Dictionary.Add("RequiredSourceItemId4", "");
            Dictionary.Add("RequiredSourceItemCount1", "");
            Dictionary.Add("RequiredSourceItemCount2", "");
            Dictionary.Add("RequiredSourceItemCount3", "");
            Dictionary.Add("RequiredSourceItemCount4", "");
            Dictionary.Add("RequiredItemId1", "");
            Dictionary.Add("RequiredItemId2", "");
            Dictionary.Add("RequiredItemId3", "");
            Dictionary.Add("RequiredItemId4", "");
            Dictionary.Add("RequiredItemId5", "");
            Dictionary.Add("RequiredItemId6", "");
            Dictionary.Add("RequiredItemCount1", "");
            Dictionary.Add("RequiredItemCount2", "");
            Dictionary.Add("RequiredItemCount3", "");
            Dictionary.Add("RequiredItemCount4", "");
            Dictionary.Add("RequiredItemCount5", "");
            Dictionary.Add("RequiredItemCount6", "");
            Dictionary.Add("RequiredSpell", "");
            Dictionary.Add("RequiredSpellCast1", "");
            Dictionary.Add("RequiredSpellCast2", "");
            Dictionary.Add("RequiredSpellCast3", "");
            Dictionary.Add("RequiredSpellCast4", "");
            Dictionary.Add("Unknown0", "");
            Dictionary.Add("ObjectiveText1", "");
            Dictionary.Add("ObjectiveText2", "");
            Dictionary.Add("ObjectiveText3", "");
            Dictionary.Add("ObjectiveText4", "");
            Dictionary.Add("RewardCurrencyId1", "");
            Dictionary.Add("RewardCurrencyId2", "");
            Dictionary.Add("RewardCurrencyId3", "");
            Dictionary.Add("RewardCurrencyId4", "");
            Dictionary.Add("RewardCurrencyCount1", "");
            Dictionary.Add("RewardCurrencyCount2", "");
            Dictionary.Add("RewardCurrencyCount3", "");
            Dictionary.Add("RewardCurrencyCount4", "");
            Dictionary.Add("RequiredCurrencyId1", "");
            Dictionary.Add("RequiredCurrencyId2", "");
            Dictionary.Add("RequiredCurrencyId3", "");
            Dictionary.Add("RequiredCurrencyId4", "");
            Dictionary.Add("RequiredCurrencyCount1", "");
            Dictionary.Add("RequiredCurrencyCount2", "");
            Dictionary.Add("RequiredCurrencyCount3", "");
            Dictionary.Add("RequiredCurrencyCount4", "");
            Dictionary.Add("QuestGiverTextWindow", "");
            Dictionary.Add("QuestGiverTargetName", "");
            Dictionary.Add("QuestTurnTextWindow", "");
            Dictionary.Add("QuestTurnTargetName", "");
            Dictionary.Add("SoundAccept", "");
            Dictionary.Add("SoundTurnIn", "");
            Dictionary.Add("DetailsEmote1", "");
            Dictionary.Add("DetailsEmote2", "");
            Dictionary.Add("DetailsEmote3", "");
            Dictionary.Add("DetailsEmote4", "");
            Dictionary.Add("DetailsEmoteDelay1", "");
            Dictionary.Add("DetailsEmoteDelay2", "");
            Dictionary.Add("DetailsEmoteDelay3", "");
            Dictionary.Add("DetailsEmoteDelay4", "");
            Dictionary.Add("EmoteOnIncomplete", "");
            Dictionary.Add("EmoteOnComplete", "");
            Dictionary.Add("OfferRewardEmote1", "");
            Dictionary.Add("OfferRewardEmote2", "");
            Dictionary.Add("OfferRewardEmote3", "");
            Dictionary.Add("OfferRewardEmote4", "");
            Dictionary.Add("OfferRewardEmoteDelay1", "");
            Dictionary.Add("OfferRewardEmoteDelay2", "");
            Dictionary.Add("OfferRewardEmoteDelay3", "");
            Dictionary.Add("OfferRewardEmoteDelay4", "");
            Dictionary.Add("RewSkillLineId", "");
            Dictionary.Add("RewSkillPoints", "");
            Dictionary.Add("RewRepMask", "");
            Dictionary.Add("RewCurrencyId1", "");
            Dictionary.Add("RewCurrencyCount1", "");
            Dictionary.Add("RewCurrencyId2", "");
            Dictionary.Add("RewCurrencyCount2", "");
            Dictionary.Add("RewCurrencyId3", "");
            Dictionary.Add("RewCurrencyCount3", "");
            Dictionary.Add("RewCurrencyId4", "");
            Dictionary.Add("RewCurrencyCount4", "");
            Dictionary.Add("ReqCurrencyId1", "");
            Dictionary.Add("ReqCurrencyCount1", "");
            Dictionary.Add("ReqCurrencyId2", "");
            Dictionary.Add("ReqCurrencyCount2", "");
            Dictionary.Add("ReqCurrencyId3", "");
            Dictionary.Add("ReqCurrencyCount3", "");
            Dictionary.Add("ReqCurrencyId4", "");
            Dictionary.Add("ReqCurrencyCount4", "");
            Dictionary.Add("QuestGiverPortraitText", "");
            Dictionary.Add("QuestGiverPortraitUnk", "");
            Dictionary.Add("QuestTurnInPortraitText", "");
            Dictionary.Add("QuestTurnInPortraitUnk", "");
            Dictionary.Add("QuestTargetMark", "");
            Dictionary.Add("QuestStartType", "");
            Dictionary.Add("StartScript", "");
            Dictionary.Add("CompleteScript", "");
            //Dictionary.Add("WDBVerified", "");

            // smart scripts
            Dictionary.Add("entryorguid", "Entry, GUID");
            Dictionary.Add("source_type", "Source type");
            //Dictionary.Add("id", "");
            Dictionary.Add("link", "Link");
            Dictionary.Add("event_type", "Event type");
            Dictionary.Add("event_phase_mask", "Event phase mask");
            Dictionary.Add("event_chance", "Event chance");
            Dictionary.Add("event_flags", "Event flags");
            Dictionary.Add("event_param1", "Event param");
            Dictionary.Add("event_param2", "Event param 2");
            Dictionary.Add("event_param3", "Event param 3");
            Dictionary.Add("event_param4", "Event param 4");
            Dictionary.Add("action_type", "Action type");
            Dictionary.Add("action_param1", "Action param");
            Dictionary.Add("action_param2", "Action param 2");
            Dictionary.Add("action_param3", "Action param 3");
            Dictionary.Add("action_param4", "Action param 4");
            Dictionary.Add("action_param5", "Action param 5");
            Dictionary.Add("action_param6", "Action param 6");
            Dictionary.Add("target_type", "Target type");
            Dictionary.Add("target_param1", "Target param");
            Dictionary.Add("target_param2", "Target param 2");
            Dictionary.Add("target_param3", "Target param 3");
            Dictionary.Add("target_x", "Target X");
            Dictionary.Add("target_y", "Target Y");
            Dictionary.Add("target_z", "Target Z");
            Dictionary.Add("target_o", "Target O");
            Dictionary.Add("comment", "Comment");

            // gameobject
            /*Dictionary.Add("guid", "");
            Dictionary.Add("id", "");
            Dictionary.Add("map", "");*/
            Dictionary.Add("zoneId", "Zone");
            Dictionary.Add("areaId", "Area");
            /*Dictionary.Add("spawnMask", "");
            Dictionary.Add("phaseMask", "");*/
            Dictionary.Add("PhaseId", "Phase");
            Dictionary.Add("PhaseGroup", "Phase group");
            /*Dictionary.Add("position_x", "");
            Dictionary.Add("position_y", "");
            Dictionary.Add("position_z", "");
            Dictionary.Add("orientation", "");*/
            Dictionary.Add("rotation0", "Rot. X");
            Dictionary.Add("rotation1", "Rot. Y");
            Dictionary.Add("rotation2", "Rot. Z");
            Dictionary.Add("rotation3", "Rot. W");
            //Dictionary.Add("spawntimesecs", "");
            Dictionary.Add("animprogress", "Anime progress");
            Dictionary.Add("state", "State");
            Dictionary.Add("displayId", "Display ID");
            Dictionary.Add("size", "Size");
            Dictionary.Add("flags", "Flags");
        }
    }
}
