//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class gameobject_template
    {
        public int entry { get; set; }
        public byte type { get; set; }
        public int displayId { get; set; }
        public string name { get; set; }
        public string IconName { get; set; }
        public string castBarCaption { get; set; }
        public string unk1 { get; set; }
        public int faction { get; set; }
        public long flags { get; set; }
        public float size { get; set; }
        public long questItem1 { get; set; }
        public long questItem2 { get; set; }
        public long questItem3 { get; set; }
        public long questItem4 { get; set; }
        public long questItem5 { get; set; }
        public long questItem6 { get; set; }
        public long data0 { get; set; }
        public int data1 { get; set; }
        public long data2 { get; set; }
        public long data3 { get; set; }
        public long data4 { get; set; }
        public long data5 { get; set; }
        public int data6 { get; set; }
        public long data7 { get; set; }
        public long data8 { get; set; }
        public long data9 { get; set; }
        public long data10 { get; set; }
        public long data11 { get; set; }
        public long data12 { get; set; }
        public long data13 { get; set; }
        public long data14 { get; set; }
        public long data15 { get; set; }
        public long data16 { get; set; }
        public long data17 { get; set; }
        public long data18 { get; set; }
        public long data19 { get; set; }
        public long data20 { get; set; }
        public long data21 { get; set; }
        public long data22 { get; set; }
        public long data23 { get; set; }
        public Nullable<int> data24 { get; set; }
        public Nullable<int> data25 { get; set; }
        public Nullable<int> data26 { get; set; }
        public Nullable<int> data27 { get; set; }
        public Nullable<int> data28 { get; set; }
        public Nullable<int> data29 { get; set; }
        public Nullable<int> data30 { get; set; }
        public Nullable<int> data31 { get; set; }
        public int unkInt32 { get; set; }
        public string AIName { get; set; }
        public string ScriptName { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
