//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEditor.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_template
    {
        public int entry { get; set; }
        public byte @class { get; set; }
        public byte subclass { get; set; }
        public sbyte SoundOverrideSubclass { get; set; }
        public string name { get; set; }
        public int displayid { get; set; }
        public byte Quality { get; set; }
        public long Flags { get; set; }
        public long FlagsExtra { get; set; }
        public float Unk430_2 { get; set; }
        public byte BuyCount { get; set; }
        public long BuyPrice { get; set; }
        public long SellPrice { get; set; }
        public byte InventoryType { get; set; }
        public int AllowableClass { get; set; }
        public int AllowableRace { get; set; }
        public int ItemLevel { get; set; }
        public byte RequiredLevel { get; set; }
        public int RequiredSkill { get; set; }
        public int RequiredSkillRank { get; set; }
        public int requiredspell { get; set; }
        public int requiredhonorrank { get; set; }
        public int RequiredCityRank { get; set; }
        public int RequiredReputationFaction { get; set; }
        public int RequiredReputationRank { get; set; }
        public int maxcount { get; set; }
        public Nullable<int> stackable { get; set; }
        public byte ContainerSlots { get; set; }
        public byte stat_type1 { get; set; }
        public short stat_value1 { get; set; }
        public int stat_unk1_1 { get; set; }
        public int stat_unk2_1 { get; set; }
        public byte stat_type2 { get; set; }
        public short stat_value2 { get; set; }
        public int stat_unk1_2 { get; set; }
        public int stat_unk2_2 { get; set; }
        public byte stat_type3 { get; set; }
        public short stat_value3 { get; set; }
        public int stat_unk1_3 { get; set; }
        public int stat_unk2_3 { get; set; }
        public byte stat_type4 { get; set; }
        public short stat_value4 { get; set; }
        public int stat_unk1_4 { get; set; }
        public int stat_unk2_4 { get; set; }
        public byte stat_type5 { get; set; }
        public short stat_value5 { get; set; }
        public int stat_unk1_5 { get; set; }
        public int stat_unk2_5 { get; set; }
        public byte stat_type6 { get; set; }
        public short stat_value6 { get; set; }
        public int stat_unk1_6 { get; set; }
        public int stat_unk2_6 { get; set; }
        public byte stat_type7 { get; set; }
        public short stat_value7 { get; set; }
        public int stat_unk1_7 { get; set; }
        public int stat_unk2_7 { get; set; }
        public byte stat_type8 { get; set; }
        public short stat_value8 { get; set; }
        public int stat_unk1_8 { get; set; }
        public int stat_unk2_8 { get; set; }
        public byte stat_type9 { get; set; }
        public short stat_value9 { get; set; }
        public int stat_unk1_9 { get; set; }
        public int stat_unk2_9 { get; set; }
        public byte stat_type10 { get; set; }
        public short stat_value10 { get; set; }
        public int stat_unk1_10 { get; set; }
        public int stat_unk2_10 { get; set; }
        public short ScalingStatDistribution { get; set; }
        public byte DamageType { get; set; }
        public int delay { get; set; }
        public float RangedModRange { get; set; }
        public int spellid_1 { get; set; }
        public byte spelltrigger_1 { get; set; }
        public short spellcharges_1 { get; set; }
        public int spellcooldown_1 { get; set; }
        public int spellcategory_1 { get; set; }
        public int spellcategorycooldown_1 { get; set; }
        public int spellid_2 { get; set; }
        public byte spelltrigger_2 { get; set; }
        public short spellcharges_2 { get; set; }
        public int spellcooldown_2 { get; set; }
        public int spellcategory_2 { get; set; }
        public int spellcategorycooldown_2 { get; set; }
        public int spellid_3 { get; set; }
        public byte spelltrigger_3 { get; set; }
        public short spellcharges_3 { get; set; }
        public int spellcooldown_3 { get; set; }
        public int spellcategory_3 { get; set; }
        public int spellcategorycooldown_3 { get; set; }
        public int spellid_4 { get; set; }
        public byte spelltrigger_4 { get; set; }
        public short spellcharges_4 { get; set; }
        public int spellcooldown_4 { get; set; }
        public int spellcategory_4 { get; set; }
        public int spellcategorycooldown_4 { get; set; }
        public int spellid_5 { get; set; }
        public byte spelltrigger_5 { get; set; }
        public short spellcharges_5 { get; set; }
        public int spellcooldown_5 { get; set; }
        public int spellcategory_5 { get; set; }
        public int spellcategorycooldown_5 { get; set; }
        public byte bonding { get; set; }
        public string description { get; set; }
        public int PageText { get; set; }
        public byte LanguageID { get; set; }
        public byte PageMaterial { get; set; }
        public int startquest { get; set; }
        public int lockid { get; set; }
        public sbyte Material { get; set; }
        public byte sheath { get; set; }
        public int RandomProperty { get; set; }
        public int RandomSuffix { get; set; }
        public int itemset { get; set; }
        public int MaxDurability { get; set; }
        public int area { get; set; }
        public short Map { get; set; }
        public int BagFamily { get; set; }
        public int TotemCategory { get; set; }
        public sbyte socketColor_1 { get; set; }
        public int socketContent_1 { get; set; }
        public sbyte socketColor_2 { get; set; }
        public int socketContent_2 { get; set; }
        public sbyte socketColor_3 { get; set; }
        public int socketContent_3 { get; set; }
        public int socketBonus { get; set; }
        public int GemProperties { get; set; }
        public float ArmorDamageModifier { get; set; }
        public long duration { get; set; }
        public short ItemLimitCategory { get; set; }
        public long HolidayId { get; set; }
        public float StatScalingFactor { get; set; }
        public long CurrencySubstitutionId { get; set; }
        public long CurrencySubstitutionCount { get; set; }
        public long flagsCustom { get; set; }
        public Nullable<short> WDBVerified { get; set; }
    }
}
